const data=[
    {
        img:'https://hblimg.mmtcdn.com//content/hubble/img/narkanda/mmt/destination/m_Narkanda_l_372_902.jpg?im=Resize=(400,462)',
        title:''
    },
    {
        img:'https://hblimg.mmtcdn.com//content/hubble/img/yercaud/mmt/destination/m_destination-yercaud-landscape_l_400_640.jpg?im=Resize=(400,462)',
        title:'',
    },
    {
        img:'https://hblimg.mmtcdn.com//content/hubble/img/dooars/mmt/destination/m_Dooars_l_457_685.jpg?im=Resize=(400,462)',
        title:'',
    },
    {
        img:'https://hblimg.mmtcdn.com//content/hubble/img/saputara/mmt/destination/m_destination-saputara-landscape_l_400_640.jpg?im=Resize=(400,462)',
        title:'',
    },
    {
        img:'https://hblimg.mmtcdn.com//content/hubble/img/dhanaulti/mmt/destination/m_Destination_Dhanaulti_l_534_801.jpg?im=Resize=(400,462)',
        title:'',
    },
    {
        img:'https://hblimg.mmtcdn.com//content/hubble/img/mandarmani/mmt/destination/m_destination-mandarmoni-landscape_l_400_640.jpg?im=Resize=(400,462)',
        title:'',
    },
    {
        img:'https://hblimg.mmtcdn.com//content/hubble/img/malvan/mmt/destination/m_Malvan_l_636_847.jpg?im=Resize=(400,462)',
        title:'',
    },
    {
        img:'https://hblimg.mmtcdn.com//content/hubble/img/yelagiri/mmt/destination/m_destination_yelagiri_landscape_l_340_544.jpg?im=Resize=(400,462)',
        title:'',
    },
    {
        img:'https://hblimg.mmtcdn.com//content/hubble/img/araku/mmt/destination/m_destination_Araku%20Valley_landscape_l_400_640.jpg?im=Resize=(400,462)',
        title:'',
    },
    {
        img:'https://hblimg.mmtcdn.com//content/hubble/img/sasan/mmt/destination/m_destination_sasan_gir_l_400_640.jpg?im=Resize=(400,462)',
        title:'',
    },
    {
        img:'https://hblimg.mmtcdn.com//content/hubble/img/udupi/mmt/destination/m_destination-udupi-landscape_l_400_640.jpg?im=Resize=(400,462)',
        title:'',
    },
    {
        img:'https://hblimg.mmtcdn.com//content/hubble/img/panchmarhi/mmt/destination/m_Destination_Panchmarhi_l_464_696.jpg?im=Resize=(400,462)',
        title:'',
    },
    {
        img:'https://hblimg.mmtcdn.com//content/hubble/img/dapoli/mmt/destination/m_Dapoli_l_703_937.jpg?im=Resize=(400,462)',
        title:'',
    },
    {
        img:'https://hblimg.mmtcdn.com//content/hubble/img/vengurla/mmt/destination/m_destination_vengurla_landscape_l_400_640.jpg?im=Resize=(400,462)',
        title:''
    },
    {
       img:'https://hblimg.mmtcdn.com//content/hubble/img/dandeli/mmt/destination/m_Destination_Dandeli_l_536_804.jpg?im=Resize=(400,462)',
       title:'' 
    },
    {
       img:'https://hblimg.mmtcdn.com//content/hubble/img/tadoba/mmt/destination/m_Tadoba_l_587_880.jpg?im=Resize=(400,462)',
       title:'' 
    },
    {
       img:'https://hblimg.mmtcdn.com//content/hubble/img/guntur/mmt/destination/m_Guntur-landscape_l_400_640.jpg?im=Resize=(400,462)',
       title:'' 
    },
    {
       img:'https://hblimg.mmtcdn.com//content/hubble/img/Bhandardara/mmt/destination/m_Bhandardara_l_568_852.jpg?im=Resize=(400,462)',
       title:'' 
    },
    {
        img:'https://hblimg.mmtcdn.com//content/hubble/img/shoghi/mmt/destination/m_Shoghi_l_667_1000.jpg?im=Resize=(400,462)',
        title:'',
    },
    {
        img:'https://hblimg.mmtcdn.com//content/hubble/img/srisailam/mmt/destination/m_srisailam-landscape_l_400_640.jpg?im=Resize=(400,462)',
        title:'',
    },
    {
        img:'https://hblimg.mmtcdn.com//content/hubble/img/vellore/mmt/destination/m_destination-vellore-landscape_l_400_640.jpg?im=Resize=(400,462)',
        title:'',
    },
    {
        img:'https://hblimg.mmtcdn.com//content/hubble/img/parwanoo/mmt/destination/m_Parwanoo_l_393_699.jpg?im=Resize=(400,462)',
        title:'',
    },
    
];

export default data